[tool.ruff]
line-length = 120
target-version = "py311"
select = ["E","F","I","B","UP"]
ignore = ["E501"]

[tool.mypy]
python_version = 3.11
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
disable_error_code = []
exclude = ["tests/"]
