line-length = 120
target-version = "py311"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # import sorting
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = [
  "E501",  # line length (handled by formatter preference)
  "UP035", # compatibility deprecation, optional
]

[lint.per-file-ignores]
  "tests/*" = [
    "E401","E402","F401","F841","E702","E741","I001","B904","E701","E722","B009","UP007"
  ]
[format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = true
