name: tests-badge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Run tests
        run: |
          pytest -q --disable-warnings --maxfail=1 > test_output.txt || true
          passed=$(grep -Eo '[0-9]+ passed' test_output.txt | awk '{print $1}')
          failed=$(grep -Eo '[0-9]+ failed' test_output.txt | awk '{print $1}')
          total=$((passed+failed))
          if [ -z "$passed" ]; then passed=0; fi
          if [ -z "$failed" ]; then failed=0; fi
          color=brightgreen
          if [ "$failed" -gt 0 ]; then color=red; fi
          echo "creating badge with $passed passed, $failed failed"
          json=$(jq -n --arg label "tests" --arg message "${passed}_passed" --arg color "$color" '{schemaVersion:1,label:$label,message:$message,color:$color}')
          echo "$json" > tests-badge.json
      - name: Upload badge artifact
        uses: actions/upload-artifact@v4
        with:
          name: tests-badge
          path: tests-badge.json
      - name: Commit badge to repo
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p badges
          mv tests-badge.json badges/tests.json
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git add badges/tests.json
          if git diff --cached --quiet; then echo "No badge changes"; else git commit -m "ci: update tests badge"; git push; fi
